const express = require("express");
const app = express();
const cors = require("cors");
const PORT = 8000;

app.use(cors());

let jayzDiscography = {
  albums: {
    "reasonable doubt": {
      released: "June 25, 1996",
      length: "55:32",
      label: "Priority-Roc-A-Fella",
      producers: [
        "Big Jaz",
        "Clark Kent",
        "DJ Irv",
        "DJ Premier",
        "Knobody",
        "Peter Panic",
        "Ski",
      ],
      certifications: "Platinum",
      tracklisting: [
        "Can't Knock the Hustle\" (featuring Mary J. Blige)",
        "Politics as Usual",
        "Brooklyn Finest (featuring The Notorious B.I.G.)",
        "Dead Presidents II",
        "Feelin' It (featuring Mecca)",
        "D'Evils",
        "22 Two's",
        "Can I Live",
        "Ain't No Nigga (featuring Foxy Brown)",
        "Friend or Foe",
        "Coming of Age (featuring Memphis Bleek)",
        "Cashmere Thoughts",
        "Bring It On (featuring Big Jaz and Sauce Money)",
        "Regrets",
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/Reasonable_Doubt_New.jpg/220px-Reasonable_Doubt_New.jpg",
    },
    "in my lifetime, vol. 1": {
      released: "November 4, 1997",
      length: "58:00",
      label: "	Roc-A-Fella-Def Jam",
      producers: [
        'Ron "Amen-Ra" Lawrence',
        "Big Jaz",
        "DJ Premier",
        "Buckwild",
        'Deric "D-Dot" Angelettie',
        "Anthony Dent",
        "Nashiem Myrick",
        "Poke and Tone",
        "Teddy Riley",
        "Ski",
        "Stevie J",
        'Daven "Prestige" Vanderpool',
        'Sean "Puffy" Combs',
      ],
      certifications: "Platinum",
      tracklisting: [
        "Intro / A Million And One Questions / Rhyme No More",
        "The City Is Mine (featuring Blackstreet)",
        "I Know What Girls Like (featuring Puff Daddy and Lil' Kim)",
        "Imaginary Player",
        "Streets Is Watching",
        "Friend or Foe '98",
        "Lucky Me",
        "(Always Be My) Sunshine (featuring Babyface and Foxy Brown)",
        "Who You Wit II",
        "Face Off (featuring Sauce Money)",
        "Real Niggaz (featuring Too $hort)",
        "Where I'm From",
        "You Must Love Me",
      ],
      imgFile:
        "https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Jayz_inmylifetime.jpg/220px-Jayz_inmylifetime.jpg",
    },
    "vol. 2... hard knock life": {
      Released: "September 29, 1998",
      Length: "61:43",
      Label: "Roc-A-Fella-Def Jam",
      producers: [
        "Irv Gotti",
        "Kid Capri",
        "J-Runnah",
        "Jermaine Dupri",
        "Rockwilder",
        "Lil' Rob",
        "Mahogany",
        "The 45 King",
        "DJ Premier",
        "Erick Sermon",
        "Stevie J",
        "Swizz Beatz",
        "Timbaland",
        'Darold "POP" Trotter',
      ],
      certifications: "5x Platinum",
      tracklisting: [
        'Intro – Hand It Down" (featuring Memphis Bleek)',
        "Hard Knock Life (Ghetto Anthem)",
        'If I Should Die" (featuring Da Ranjahz)',
        "Ride or Die",
        'Nigga What, Nigga Who (Originator 99)" (featuring Big Jaz)',
        'Money, Cash, Hoes" (featuring DMX)',
        'A Week Ago" (featuring Too $hort)',
        'Coming of Age (Da Sequel)" (featuring Memphis Bleek)',
        'Can I Get A..." (featuring Ja Rule and Amil)',
        'Paper Chase" (featuring Foxy Brown)',
        'Reservoir Dogs" (featuring The LOX, Beanie Sigel and Sauce Money)',
        "It's Like That\" (featuring Kid Capri)",
        "It's Alright\" (featuring Memphis Bleek)",
        "Money Ain't a Thang\" (featuring Jermaine Dupri)",
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/Jay-z-vol-2-hard-knock-life.jpg/220px-Jay-z-vol-2-hard-knock-life.jpg",
    },
    "vol. 3... life and times of s. carter": {
      Released: "December 28, 1999",
      Length: "71:05",
      Label: "Roc-A-Fella-Def Jam",
      producers: [
        'Darrell "Digga" Branch',
        "Clue",
        "DJ Premier",
        "DURO",
        "Irv Gotti",
        "K Rob",
        "Lil Rob",
        "Chauncey Mahan",
        "P. Skam",
        "Rockwilder",
        'Russell "Russ" Howard',
        'Sean "SAF" Francis',
        "Sam Sneed",
        "Swizz Beatz",
        "Timbaland",
        "Lance Rivera",
      ],
      certifications: "3× Platinum",
      tracklisting: [
        "Hova Song (Intro)",
        "So Ghetto",
        'Do It Again (Put Ya Hands Up)" (featuring Amil and Beanie Sigel)',
        "Dope Man",
        'Things That U Do" (featuring Mariah Carey)',
        "It's Hot (Some Like It Hot)",
        'Snoopy Track" (featuring Juvenile)',
        'S. Carter" (featuring Amil)',
        'Pop 4 Roc" (featuring Beanie Sigel, Memphis Bleek and Amil)',
        'Watch Me" (featuring Dr. Dre)',
        "Big Pimpin'\" (featuring UGK)",
        "There's Been a Murder",
        "Come and Get Me",
        "Hova Song (Outro)",
        "Jigga My Nigga",
        "Girl's Best Friend",
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/Jay-z-vol-3-life-and-times-s-carter.jpg/220px-Jay-z-vol-3-life-and-times-s-carter.jpg",
    },
    "the dynasty: roc la familia": {
      Released: "October 31, 2000",
      Length: "66:35",
      Label: "Roc-A-Fella-Def Jam",
      producers: [
        "B-High','Bink!','Just Blaze','Memphis Bleek','The Neptunes','Rick Rock','Rockwilder','T.T.','Kanye West",
      ],
      certifications: "2× Platinum",
      tracklisting: [
        "Intro",
        'Change the Game" (performed by Jay-Z, Beanie Sigel and Memphis Bleek)',
        "I Just Wanna Love U (Give It 2 Me)",
        'Streets Is Talking" (performed by Jay-Z and Beanie Sigel)',
        "This Can't Be Life\" (performed by Jay-Z and Beanie Sigel featuring Scarface)",
        'Get Your Mind Right Mami" (performed by Jay-Z and Memphis Bleek featuring Snoop Dogg)',
        'Stick 2 the Script" (performed by Jay-Z and Beanie Sigel)',
        'You, Me, Him and Her" (performed by Dynasty)',
        'Guilty Until Proven Innocent" (featuring R. Kelly)',
        "Parking Lot Pimpin'\" (performed by Jay-Z, Beanie Sigel and Memphis Bleek)",
        'Holla" (performed by Memphis Bleek)',
        '1-900-Hustler" (performed by Jay-Z, Beanie Sigel and Memphis Bleek featuring Freeway)',
        'The R.O.C." (performed by Beanie Sigel and Memphis Bleek)',
        "Soon You'll Understand",
        "Squeeze 1st",
        'Where Have You Been" (performed by Jay-Z and Beanie Sigel)',
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/4/40/Jay-z-dynasty-roc-la-familia-2000.jpg",
    },
    "the blueprint": {
      released: "September 11, 2001",
      length: "63:25",
      label: "Roc-A-Fella-Def Jam",
      producers: [
        "Bink",
        "Eminem",
        "Just Blaze",
        "Timbaland",
        "The Trackmasters",
        "Kanye West",
      ],
      certifications: "2× Platinum",
      tracklisting: [
        "The Ruler's Back",
        "Takeover",
        "Izzo (H.O.V.A.)",
        "Girls, Girls, Girls",
        "Jigga That Nigga",
        "U Don't Know",
        "Hola' Hovito",
        "Heart of the City (Ain't No Love)",
        "Never Change",
        "Song Cry",
        "All I Need",
        'Renegade" (featuring Eminem)',
        "Blueprint (Momma Loves Me)",
        "Breathe Easy (Lyrical Exercise)",
        "Girls, Girls, Girls (Part 2)",
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/thumb/2/2c/The_Blueprint.png/220px-The_Blueprint.png",
    },
    "jay-Z:unplugged": {
      released: "December 18, 2001",
      length: "58:15",
      label: "	Roc-A-Fella-Def Jam",
      producers: ["Questlove", "The Roots", "Ski"],
      certifications: "Gold",
      tracklisting: [
        "Izzo (H.O.V.A.)",
        "Takeover",
        "Girls, Girls, Girls",
        "Jigga What, Jigga Who",
        "Big Pimpin'",
        "Heart of the City (Ain't No Love)",
        "Can I Get A...",
        "Hard Knock Life (Ghetto Anthem)",
        "Ain't No Nigga",
        "Can't Knock the Hustle" / 'Family Affair" (featuring Mary J. Blige)',
        "Song Cry",
        'I Just Wanna Love U (Give It 2 Me)" (featuring Pharrell) ',
        "Jigga That Nigga" / "People Talking",
      ],
      imgFile:
        "https://upload.wikimedia.org/wikipedia/en/thumb/2/20/Jay-z-mtv-unplugged.jpg/220px-Jay-z-mtv-unplugged.jpg",
    },
    "the Best of both worlds": {
      Released: "March 19, 2002",
      Length: "49:16",
      Label: "Roc-A-Fella-Island Def Jam-RocklandJive",
      producers: ["Poke and Tone','Megahertz','Charlemagne"],
      certifications: "5x Platinum",
      tracklisting: [
        "The Best of Both Worlds",
        "Take You Home With Me",
        "Break Up to Make Up",
        "It Ain't Personal",
        "The Streets",
        'Green Light" (featuring Beanie Sigel)',
        "Naked (R. Kelly solo)",
        "Shake Ya Body\" (featuring Lil' Kim)",
        "Somebody's Girl",
        "Get This Money",
        "Shorty",
        "Honey",
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/a/af/Jay-Z%26R.KellyBestofBothWorlds.jpg",
    },
    "unfinished business": {
      Released: "October 26, 2004",
      Length: "44:34",
      Label: "Roc-A-Fella-Def Jam-Rockland-Jive",
      producers: ["Alexander Mosley"],
      certifications: "Platinum",
      tracklisting: [
        "The Return",
        "Big Chips",
        "We Got 'Em Goin'\" (featuring Memphis Bleek)",
        "She's Coming Home with Me",
        "Feelin' You in Stereo",
        'Stop" (featuring Foxy Brown)',
        "Mo' Money\" (featuring Twista)",
        "Pretty Girls",
        "Break Up (That's All We Do)",
        "Don't Let Me Die",
        'The Return (Remix)" (featuring Slick Rick and Doug E. Fresh)',
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/thumb/2/26/Unfinished_BusinessJay-Z%26R.Kelly.jpg/220px-Unfinished_BusinessJay-Z%26R.Kelly.jpg",
    },
    "collision course": {
      Released: "November 30, 2004",
      Length: ["21:15 (CD)", "45:01 (DVD)"],
      Label: "Roc-A-Fella-Machine Shop-Warner Bros-Def Jam",
      producers: ["Mike Shinoda"],
      certifications: "2× Platinum",
      tracklisting: [
        "Dirt off Your Shoulder / Lying from You",
        "Big Pimpin' / Papercut",

        "Jigga What / Faint",
        "Numb / Encore",
        "Izzo / In the End",
        "Points of Authority / 99 Problems / One Step Closer",
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/2/2f/Collision_Course_CD-DVD_cover.jpg",
    },
    "kingdom come": {
      released: "November 21, 2006",
      length: "59:21",
      label: "Priority-Roc-A-Fella",
      producers: [
        "B-Money",
        "Mark Batson",
        "DJ Khalil",
        "Dr. Dre",
        "Just Blaze",
        "The Neptunes",
        "Chris Martin",
        "Rik Simpson",
        "Swizz Beatz",
        "Syience",
        "Kanye West",
      ],
      certifications: "2× Platinum",
      tracklisting: [
        "The Prelude",
        "Oh My God",
        "Kingdom Come",
        "Show Me What You Got",
        'Lost One" (featuring Chrisette Michele)',
        'Do U Wanna Ride" (featuring John Legend)',
        "30 Something",
        "I Made It",
        'Anything" (featuring Usher and Pharrell)',
        'Hollywood" (featuring Beyoncé)',
        "Trouble",
        'Dig a Hole" (featuring Sterling Simms)',
        'Minority Report" (featuring Ne-Yo)',
        'Beach Chair" (featuring Chris Martin)',
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/5/56/Jay-Z_-_Kingdom_Come.png",
    },
    "american gangster": {
      released: "November 6, 2007",
      length: "58:38",
      label: "	Roc-A-Fella-Def Jam",
      producers: [
        'Sean "Diddy" Combs\' with The Hitmen',
        "Bigg D",
        "Chris Flame",
        'Idris "Driis" Elba',
        "Jermaine Dupri",
        "Just Blaze",
        "Skyz Muzik",
        "The Neptunes",
        "No I.D.",
        "Toomp",
        "Mario Winans",
      ],
      certifications: "Platinum",
      tracklisting: [
        'Intro" (performed by Idris Elba)',
        "Pray",
        "American Dreamin",
        'Hello Brooklyn 2.0" (featuring Lil Wayne)',
        "No Hook",
        "Roc Boys (And the Winner Is)...",
        "Sweet",
        "I Know",
        "Party Life",
        'Ignorant Shit" (featuring Beanie Sigel)',
        "Say Hello",
        'Success" (featuring Nas)',
        "Fallin'",
        'Blue Magic" (bonus track)',
        'American Gangster" (bonus track)',
      ],
      imgFile:
        "https://upload.wikimedia.org/wikipedia/en/6/6a/Jay-Z_-_American_Gangster.png",
    },
    "the blueprint 3": {
      Released: "	September 8, 2009",
      Length: "	60:44",
      Label: "Roc Nation-Asylum-Atlantic",
      producers: [
        "No I.D.",
        "Shux",
        "Janet Sewell-Ulepic",
        "Angela Hunte",
        "The Inkredibles",
        "Swizz Beatz",
        "Timbaland",
        "J-Roc",
        "Kenoe",
        "Jeff Bhasker",
        "The Neptunes",
      ],
      certifications: "Platinum",
      tracklisting: [
        "What We Talkin' About\" (featuring Luke Steele)",
        "Thank You",
        "D.O.A. (Death of Auto-Tune)",
        'Run This Town" (featuring Rihanna and Kanye West)',
        'Empire State of Mind" (featuring Alicia Keys)',
        'Real as It Gets" (featuring Jeezy)',
        'On to the Next One" (featuring Swizz Beatz)',
        'Off That" (featuring Drake)',
        'A Star Is Born" (featuring J. Cole)',
        "Venus vs. Mars",
        'Already Home" (featuring Kid Cudi)',
        'Hate" (featuring Kanye West)',
        "Reminder",
        'So Ambitious" (featuring Pharrell)',
        'Young Forever" (featuring Mr Hudson)',
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/thumb/b/bb/Jay-Z_-_The_Blueprint_3.jpg/220px-Jay-Z_-_The_Blueprint_3.jpg",
    },
    "watch the throne": {
      Released: "August 8, 2011",
      Length: "46:12",
      Label: "Def Jam-Roc Nation-Roc-A-Fella",
      producers: [
        "Kanye West",
        "88-Keys",
        "Hit-Boy",
        "Pete Rock",
        "Jeff Bhasker",
        "Mike Dean",
        "The Neptunes",
        "Q-Tip",
        "RZA",
        "Sak Pase",
        "Swizz Beatz",
        "S1Southside",
        "Lex Luger",
      ],
      certifications: "5× Platinum",
      tracklisting: [
        'No Church in the Wild" (featuring Frank Ocean & The-Dream)',
        'Lift Off" (featuring Beyoncé)',
        "Niggas in Paris",
        'Otis" (featuring Otis Redding)',
        "Gotta Have It",
        "New Day",
        "That's My Bitch",
        "Welcome to the Jungle",
        "Who Gon Stop Me",
        "Murder to Excellence",
        'Made in America" (featuring Frank Ocean)',
        'Why I Love You" (featuring Mr Hudson)',
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/thumb/e/ee/Watch_The_Throne.jpg/220px-Watch_The_Throne.jpg",
    },
    "magna carta holy grail": {
      Released: "July 4, 2013",
      Length: "66:55",
      Label: "Roc-A-Fella-Roc Nation-UMD-The Island Def Jam Music Group",
      producers: [
        "Boi-1da",
        'Darhyl "Hey DJ" Camper',
        "Hit-Boy",
        'Jerome "Jroc" Harmon',
        "Justin Timberlake",
        'Kyambo "Hip Hop" Joshua',
        "Marz",
        "Mike Dean",
        "Mike Will Made It",
        "No I.D.",
        "Pharrell Williams",
        "Swizz Beatz",
        "The-Dream",
        "Timbaland",
        "Travis Scott",
        "Vinylz",
        "WondaGurl",
      ],
      certifications: "2× Platinum",
      tracklisting: [
        'Holy Grail" (featuring Justin Timberlake)',
        "Picasso Baby",
        "Tom Ford",
        'Fuckwithmeyouknowigotit" (featuring Rick Ross)',
        'Oceans" (featuring Frank Ocean)',
        "F.U.T.W.",
        "Somewhereinamerica",
        "Crown",
        "Heaven",
        "Versus",
        'Part II (On the Run)" (featuring Beyoncé)',
        "Beach Is Better",
        "BBC",
        "JAY Z Blue",
        "La Familia",
        "Open Letter",
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/en/thumb/8/87/Magna_Carta_Holy_Grail_cover.png/220px-Magna_Carta_Holy_Grail_cover.png",
    },
    "4:44": {
      released: "June 30, 2017",
      length: "36:11",
      label: "Roc Nation",
      producers: ["Dominic Maker", "James Blake"],
      certifications: "Platinum",
      tracklisting: [
        "Kill Jay Z",
        "The Story of O.J.",
        'Smile" (featuring Gloria Carter)',
        'Caught Their Eyes" (featuring Frank Ocean)',
        "4:44",
        'Family Feud" (featuring Beyoncé)',
        'Bam" (featuring Damian Marley)',
        "Moonlight",
        "Marcy Me",
        "Legacy",
      ],
      imgUrl:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/4-44_album_cover.png/220px-4-44_album_cover.png",
    },
    // unknown: {
    //   released: "unknown",
    //   length: "unknown",
    //   label: "unknown",
    //   producers: ["unknown"],
    //   certifications: "unknown",
    //   tracklisting: ["unknown"],
    //   imgUrl: "unknown",
    // },
  },
};

app.get("/", (req, res) => {
  res.sendFile(__dirname + "/index.html");
});

app.get("/api", (request, response) => {
  // const albumName = request.params.albumName.toLowerCase();
  // if (jayzDiscography.albums[albumName]) {
  //   response.json(jayzDiscography.albums[albumName]);
  // } else {
  //   response.json(jayzDiscography.albums['unknown']);
  // }
  response.json(jayzDiscography)
});

app.listen(process.env.PORT || PORT, () => {
  console.log(`Server running on port ${PORT}`);
});

// ":albumName"
